services:
  # This is the name of your service.
  app:
    # Build the Docker image from the Dockerfile in the current directory.
    build: .
    ports:
      # Map the host port to the container port.
      # The syntax ${PORT:-10000} means "use the PORT env var if it exists, otherwise default to 10000".
      - "${PORT:-9030}:9030"
    environment:
      # --- Database Configuration ---
      # These values are derived from your Neon connection string.
      # For better security, you should move these to Render's "Secret Files".
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-super-glitter-a1mlhsda-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_kGSVXigr1T3Z

      # --- LangChain4j Google AI API Key ---
      # This MUST be set as a secret environment variable in your Render dashboard.
      # Render will inject the value at runtime.
      GOOGLE_AI_GEMINI_API_KEY: ${GOOGLE_AI_GEMINI_API_KEY}

      # --- Server Port ---
      # This now matches Render's behavior for consistency.
      PORT: ${PORT:-9030}